nginx:
  enabled: true
  chart: "bitnami/nginx"
  service:
    type: ClusterIP
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  ingress:
    enabled: true
    hostname: nginx-e27db1-prod.apps.emerald.devops.gov.bc.ca
  version: "15.11.0"
  image:
    pullPolicy: Always
  podLabels:
    environment: prod
    env: production
    owner: "jojo-team"
    project: "abcd"
    DataClass: "Medium"
  commonLabels:
    environment: prod
    env: production
    owner: "jojo-team"
    project: "abcd"
    DataClass: "Medium"
  replicaCount: 2

postgresql:
  enabled: true
  image:
    pullPolicy: Always
  commonLabels:
    environment: prod
    env: production
    owner: "jojo-team"
    project: "abcd"
    DataClass: "Medium"
  primary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    labels:
      environment: prod
      env: production
      owner: "jojo-team"
      project: "abcd"
      DataClass: "Medium"
    podLabels:
      environment: prod
      env: production
      owner: "jojo-team"
      project: "abcd"
      DataClass: "Medium"
  replicaCount: 2
