project: e27db1
kind: Application
metadata:
  name: jojo-gitops-prod
spec:
  destination:
    name: ''
    namespace: e27db1-prod
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/jojo-gitops
    repoURL: 'git@github.com:bcgov-c/tenant-gitops-e27db1.git'
    targetRevision: main
    helm:
      valueFiles:
        - $values/deploy/prod_values.yaml
  project: e27db1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true